services:
  odoo-17a:
    container_name: odoo-17a
    image: odoo:17.0
    env_file: .env
    ports:
      - "8082:8069"
    volumes:
      - ./etc/odoo:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./var/lib/odoo:/var/lib/odoo
    depends_on:
      - odoo17a-postgres
    networks:
      - odoo17a-network

  odoo17a-postgres:
    container_name: odoo17a-postgres
    image: postgres:17
    env_file: .env
    volumes:
      - ./var/lib/postgresql/data/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - odoo17a-network

networks:
  odoo17a-network:
    driver: bridge
